apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-connect-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    -
  claimRef:
    name: kafka-connect-pvc
    namespace: kafka-connect