apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-connect-pvc
  namespace: kafka-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
