apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect-cluster.fullname" . }}
  labels:
    {{- include "kafka-connect-cluster.labels" . | nindent 4 }}
data:
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: "kafka-connect"
  CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
  CONNECT_PLUGIN_PATH: "/usr/share/java/kafka,/usr/share/confluent-hub-components,/data/connect-jars,/usr/share/java/kafka/debezium-connector-mysql"
