apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect-cluster.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-connect-cluster.labels" . | nindent 4 }}
data:
  CONNECT_GROUP_ID: "kafka-connect"
  CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_PLUGIN_PATH: "/usr/share/java/kafka,/usr/share/confluent-hub-components,/data/connect-jars,/usr/share/java/kafka/custom-plugin"
  {{- with .Values.kafkaConnect.env.data }}
    {{ toYaml . | nindent 2 }}
  {{- end }}
