apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    {{- toYaml .Values.pv.accessModes | nindent 4}}
  claimRef:
    name: {{ .Values.pvc.name }}
    namespace: {{ .Values.namespace }}
  mountOptions:
    {{- toYaml .Values.pv.mountOptions | nindent 4}}
  nfs:
    path: {{ .Values.pv.path }}
    server: {{ .Values.pv.server }}
    readOnly: true
  persistentVolumeReclaimPolicy: Retain
