apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kafka-connect-cluster.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-connect-cluster.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
